import{a as h,S as g,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const L="51687236-e99e958891c77c47ce6f4e325",q="https://pixabay.com/api/";function b(e,r=1){return h.get(q,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(i=>i.data)}let c=null;function S(e){const r=document.querySelector(".gallery"),i=e.map(s=>`
        <li class='gallery-item'>
            <a href='${s.largeImageURL}'>
                <img class='gallery-img' src='${s.webformatURL}' alt='${s.tags}'>
                <ul class='gallery-item-info'>
                    <li class='text-info'>Likes<span class='text-info-data'>${s.likes}</span></li>
                    <li class='text-info'>Views<span class='text-info-data'>${s.views}</span></li>
                    <li class='text-info'>Comments<span class='text-info-data'>${s.comments}</span></li>
                    <li class='text-info'>Downloads<span class='text-info-data'>${s.downloads}</span></li>
                </ul>
            </a>
        </li>
    `).join("");r.insertAdjacentHTML("beforeend",i),c?c.refresh():c=new g(".gallery a",{})}function x(){document.querySelector(".gallery").innerHTML=""}function v(){var e;(e=document.querySelector(".loader"))==null||e.classList.remove("hidden")}function f(){var e;(e=document.querySelector(".loader"))==null||e.classList.add("hidden")}function w(){var e;(e=document.querySelector(".load-more"))==null||e.classList.remove("hidden")}function m(){var e;(e=document.querySelector(".load-more"))==null||e.classList.add("hidden")}const y=document.querySelector("form"),P=document.querySelector(".load-more");let u="",n=1,d=0;const E=15;async function p(e=!1){v(),e&&x();try{const r=await b(u,n);if(f(),e&&!r.hits.length){m(),l.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter"});return}if(S(r.hits),!e){const i=document.querySelector(".gallery-item").getBoundingClientRect();i&&window.scrollBy({top:i.height*2,behavior:"smooth"})}e&&(d=r.totalHits),n*E>=d||!r.hits.length?(m(),l.info({title:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):w()}catch(r){f(),l.error({title:"Error happened"}),console.error(r)}}y.addEventListener("submit",e=>{e.preventDefault(),u=y.querySelector("input").value.trim(),u&&(n=1,d=0,p(!0))});P.addEventListener("click",()=>{n++,p()});
//# sourceMappingURL=index.js.map
